"""change name column in favorite_games

Revision ID: 852ff8fe06a1
Revises: baa5a8a5d283
Create Date: 2023-09-07 13:08:42.873657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852ff8fe06a1'
down_revision = 'baa5a8a5d283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_rawg_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id_game_rawg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_game_rawg', sa.INTEGER(), nullable=False))
        batch_op.drop_column('game_rawg_id')

    # ### end Alembic commands ###
